language: java
sudo: false
script: mvn install
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "therealwaluigi"
  - git config --local user.email "nicolas.haemmerli@gmx.ch"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: mqOQkPV7awnFzTg03fmAH/xBJqitLVQjbz5CY+yEGkNtsx4J1O0uob3esiQQhj55mddvFebBfwJ2YDxk/pdMS/oROev+ppTzhTWRA7lmX5OQXZxBZCNfR5l7QaquYnJP2VcFTy5gecd8caTaDW3rsiAHb6UCMtMI4Ua64LnP2hSI+8lUMURtkAPkcCO/VyMNc7QpobXD45J4cw08lR4tA1de+RVeYjKPlb2GLoX6gREkIvVcqLAn4zEE7owO3wURCxp0U0Wp6EZuH4NkkDe+rn7BncmL0BzGSKx5fZyb1mYLGevHhuW0Hqjh5CIvd/w7mvogMFopU0vEFkJgn/1wRdaqF8uGlGd8E5JAMUyOYC7Cpk0E3Q6CTIfYZvUJWMvTnWU8qpnl/dSPY5+xTSOk3b1WxaAvRv+Ae3oSO7YEYetxqtVcmsTwW9dFDJ4LnOPmHhr4otsFoQ+RZFM9iTu/IcXJCfWIhJWhJccNEbNHMaD0Z1yeP1iRZkVOq/qlRjglTpJfwbs1EFA1UZgpcobs8xPoONtRjMKNcbV2CBwVKvWKBUOrHzBek7Vj+ec4YxDwQpLNt6x8B/ccWlfVr3EmHlz2CQOhlzUa08SvrsEH0+QcSwgvVg5/wHZMBmPuFQz6MYSqmL0BoNVRkyelX772ptqdEEbG0mTMsT42sbzTPtw=
  file: "/home/travis/.m2/repository/ch/bbw/02_ConsoleCalculatorWithMaven/0.0.1-SNAPSHOT/02_ConsoleCalculatorWithMaven-0.0.1-SNAPSHOT.jar"
  on:
    repo: therealwaluigi/calculator
  skip_cleanup: true